### ISSUE TITLE
Change error text when Viav controls are used outside of Viav text channel

### ISSUE THREAD

**Issue by LudusLight** [BrokenLamp/viav#73]
At the moment the error just says "Error". Something better would be "You can only use this command inside of a Viav text channel".

Thank you Walking_Deadites#9898 for the report

**Comment by BrandonDyer64** [comment]
A ticket cannot be both a bug _and_ an enhancement.

**Comment by BrandonDyer64** [comment]
Fixed in 12741684abfdad54b99d4256a6017dc3673c6444
